import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Sidebar } from '@/components/Sidebar';
import { css } from '../../styled-system/css';
import { CounterStoreProvider } from '@/providers/counter-store-provider';
import { ThemeProvider } from '@/providers/theme-provider';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// 레이아웃 스타일
const layoutContainerStyle = css({
  display: 'flex',
  minH: '100vh',
  bg: 'bg',
});

const mainContentStyle = css({
  flex: 1,
  overflow: 'auto',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' suppressHydrationWarning>
      <head>
        {/* 테마 유지 스크립트 */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  if (theme === 'light' || theme === 'dark') {
                    document.documentElement.setAttribute('data-theme', theme);
                  } else {
                    document.documentElement.setAttribute('data-theme', 'light');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <CounterStoreProvider>
            <div className={layoutContainerStyle}>
              <Sidebar />
              <main className={mainContentStyle}>{children}</main>
            </div>
          </CounterStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
