import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import './globals.css';
import { Sidebar } from '@/components/Sidebar';
import { css } from '../../styled-system/css';
import { CounterStoreProvider } from '@/providers/counter-store-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import { parseUICookie } from '@/lib/parse-ui-cookie';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// 레이아웃 스타일
const layoutContainerStyle = css({
  display: 'flex',
  minH: '100vh',
  bg: 'bg',
});

const mainContentStyle = css({
  flex: 1,
  overflow: 'auto',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 서버에서 쿠키를 읽어 초기 상태 파싱
  const cookieStore = await cookies();
  const uiCookie = cookieStore.get('ui-storage');
  const initialUIState = parseUICookie(uiCookie?.value);

  return (
    <html
      lang='ko'
      suppressHydrationWarning
      data-theme={initialUIState.theme}
      data-sidebar-collapsed={String(initialUIState.isSidebarCollapsed)}
    >
      <head />
      <body className={inter.className}>
        <ThemeProvider>
          <CounterStoreProvider>
            <div className={layoutContainerStyle}>
              <Sidebar
                initialCollapsed={initialUIState.isSidebarCollapsed}
                initialTheme={initialUIState.theme}
              />
              <main className={mainContentStyle}>{children}</main>
            </div>
          </CounterStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
